---
title: "Forums"
author: "Jason"
date: "4/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## This contains code to and from various forums
```{r ---> Overall ANOVA with PostHoc testing, eval=TRUE, echo=TRUE}
library(gt)
library(tidyverse)
library(reprex)
library(here)
here()
dr_here(show_reason = FALSE)
#	PostHoc DOES WORK

# construct anova model for each column of dat[, my_outcome_variables]
z_dat <- iris

z_model_summaries <- z_dat[1:4] %>%
  purrr::map(~ aov(.x ~ Species, data = z_dat))  %>%
  # append the TukeyHSD CI estimates
  purrr::map(function(x) {
    list(
      model = x,
      tukey = TukeyHSD(x)
    )
  })




```



```{r ---> RETURN TABLES OF RESULTS}
####		THIS RETURNS THE RESULTS OF THE OVERALL ANOVA	####
GetModels <- function(l) l$model
z_Models <- purrr::map(z_model_summaries, GetModels) %>% 
  purrr::map_dfr(broom::tidy, .id = "Name")
head(z_Models)

##		TABLE OF OVERALL EFFECTS
filter(z_Models,  term !="Residuals") %>%
	dplyr::select("Name" , "p.value")  %>%
	gt(rowname_col = "Name") %>%
	tab_header(
		title = md("Main effect of group"))  %>% 
	fmt_number(
		columns = vars("p.value"),
		decimals = 4
	)


####		RETRIEVE POSTHOC COMPARISONS		####
GetTukeys <- function(m) m$tukey
z_Tukeys  <- purrr::map(z_model_summaries, GetTukeys)  %>% 
	purrr::map_dfr(broom::tidy, .id = "Name")
head(z_Tukeys)

####		SIMPLE RENAME		####
names(z_Tukeys)[names(z_Tukeys) == 'Name'] <- 'Var'
names(z_Tukeys)[names(z_Tukeys) == 'estimate'] <- 'diff'

####		GT TABLE OF POSTHOC COMPARISONS
select(z_Tukeys, -term) %>% 
	gt(groupname_col = "Var") %>% 
	tab_header(
		title = md("*PostHoc*")
		) %>% 
	tab_stubhead(label = "Group Comps") %>% 
	fmt_number(
		columns = vars("diff", "conf.low", "conf.high"),
		decimals = 2)  %>% 
	fmt_number(#,
		columns = vars("adj.p.value"),
		decimals = 4)




```


```{r ---> kable-1}
suppressPackageStartupMessages(library(tidyverse))
library(kableExtra)

formatme <- tribble(
  ~estimate, ~P_value, 
   14.93423,  1.064325e-173, 
   -5.58189,  3.863223e-08 , 
   -4.00146,  0.01792431   , 
   -1.64129,  0.1321123    , 
   -5.32435,  1.282435e-06 , 
   -4.81021,  1.634358e-05 , 
   -0.97118,  0.373213     , 
   -2.12204,  0.051729     , 
   -1.88072,  0.1          , 
   -1.71032,  0.116
)





# formatme %>% 
#   mutate(
#     P_value = cell_spec(
#       if_else(
#         P_value < 1e-02, 
#         formatC(P_value, digits = 2, format = "e"),
#         formatC(P_value, digits = 2, format = "f")
#       ),
#       format = "html",
#       color = ifelse(P_value <= 0.05, yes = "red", no = "blue"),
#       escape = FALSE)) %>%
#   mutate_if(
#     is.numeric, 
#     function(x) {
#       cell_spec(
#         formatC(x, digits = 2, format = "f", drop0trailing = FALSE),
#         format = "html"
#       )
#     }
#   )


# format2 <- formatme 

formatme %>%
	mutate(
		P_value = if_else(
			P_value < 0.01,
			formatC(P_value, digits = 2, format = "e"),
			formatC(P_value, digits = 2, format = "f", drop0trailing = FALSE)
		)
	) %>%
	mutate_if(
		is.numeric,
		function(x) {
			formatC(x, digits = 2, format = "f", drop0trailing = FALSE)
		}
	)



kable(mtcars[1:10, 1:6], caption = "Group Rows") %>%
  kable_styling("striped", full_width = F) %>%
  pack_rows(index = c(" " = 0, "Group 1" = 2, "Group 2" = 3))

kable(mtcars[1:10, 1:6], caption = "Group Rows") %>%
  kable_styling("striped", full_width = F) %>%
  pack_rows(index = c(" " = 2, "Group 1" = 2, "Group 2" = 3))

```


```{r ---> kable2 }


# format2 %>% 
#   mutate(
#     P_value = cell_spec(
#       if_else(
#         P_value < 1e-02, 
#         formatC(P_value, digits = 2, format = "e"),
#         formatC(P_value, digits = 2, format = "f")
#       ),
#       format = "html",
#       color = ifelse(P_value <= 0.05, yes = "red", no = "blue"),
#       escape = F
#     )
#   ) %>%
#   mutate_if(
#     is.numeric, 
#     function(x) {
#       cell_spec(
#         formatC(x, digits = 2, format = "f", drop0trailing = FALSE),
#         format = "html"
#       )
#     }
#   )

```
