---
title: "Knit for RStudio forum"
author: "Jason"
date: "3/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r ---> Libraries}
library(doBy)
library(fuzzyjoin)
library(reshape2)
library(varhandle)
library(multcomp)
library(car)
library(lattice)
library(Formula)
library(Hmisc)
library(ggpubr)
library(tidyverse)
library(reprex)
library(knitr)
library(pander)
library(here)
here()
dr_here(show_reason = FALSE)
#		DONE AS OF March 17, 2020
```

```{r ---> Import data}
# Small dataset
sm.dat <- read.csv(url('https://github.com/BrainStormCenter/Brad_PT/smData_v1.csv'), 
				   header = TRUE)

```

##	EXAMINE DATA

###	BDI
```{r ---> BDI Summary}
#		BDI VARIABLES
sm.dat.bdi <- sm.dat[c(1:2,grep("bdi", colnames(dat1)))]
view(dat.bdi)

sm.bdi.smry1  <- sm.dat %>%
	group_by(group.factor) %>%
	summarise(
		count = n(),
		avg.bdi.tot = mean(bdi_total, na.rm = TRUE),
		sd.bdi.tot = sd(bdi_total, na.rm = TRUE)
		# avg.pdi.tot = mean(bdi_total, na.rm = TRUE),
		# sd.pdi.tot = sd(pdi_total, na.rm = TRUE)
	)
view(bdi.smry1)
