---
title: "knit issues April 28, 2020"
author: "Jason"
date: "4/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r ---> Libraries, eval=TRUE, echo=FALSE, results=FALSE, collapse=TRUE, message=FALSE}
library(knitr)
library(kableExtra)
library(tidyverse)
library(reprex)
library(here)
here()
dr_here(show_reason = FALSE)


```


```{r ---> Create-data, eval=TRUE, echo=FALSE, message=FALSE}

zq.dat <- structure(list(group = structure(c(1L, 1L, 1L, 1L, 1L, 
1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 
2L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 1L, 2L, 1L, 2L, 
1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 2L, 2L, 2L), .Label = c("HC", 
"CLBP", "FM", "TRUE"), class = "factor"), sex = structure(c(1L, 
1L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 
2L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 
2L), .Label = c("Female", "Male"), class = "factor"), slpQual = c(0, 
1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 
2, 0, 2, 1, 1, 2, 1, 2, 1, 1, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 1, 
1, 1, 2, 1, 0, 1, 0), slpLat = c(1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 
1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 0, 1, 1, 1, 2, 0, 
2, 1, 1, 2, 1, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 0), slpDur = c(1, 
0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 
1, 0, 2, 1, 1, 0, 1, 3, 1, 0, 1, 1, 2, 1, 2, 0, 0, 1, 2, 1, 0, 
1, 1, 1, 1, 1, 1, 0), slpEff = c(0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 
0, 0, 0, 3, 3, 0, 3, 1, 0, 0, 3, 0, 0, 3, 1, 3, 0, 1, 1, 3, 3, 
0, 3, 3, 1, 0, 2, 0, 0, 1, 3, 3, 3, 0, 3, 0, 0, 0, 1, 0), slpDist = c(1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1), slpMeds = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 3, 1, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 2, 1, 0, 0, 0, 0, 3, 0, 0), 
    slpDayFcn = c(0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1), psqi_Global = c(3, 
    3, 7, 3, 5, 4, 3, 4, 2, 6, 1, 4, 4, 6, 7, 1, 7, 5, 6, 4, 
    5, 2, 6, 4, 8, 6, 4, 5, 8, 12, 6, 4, 6, 7, 7, 4, 8, 1, 1, 
    8, 8, 11, 9, 5, 8, 5, 5, 7, 5, 2), ess_total = c(5, 5, 4, 
    7, 10, 2, 5, 5, 4, 9, 6, 10, 8, 9, 6, 8, 9, 3, 6, 10, 8, 
    10, 3, 0, 10, 6, 6, 6, 9, 6, 6, 4, 3, 5, 3, 6, 6, 5, 1, 1, 
    3, 11, 3, 8, 8, 4, 7, 8, 5, 11), bdi_total = c(0, 1, 1, 13, 
    5, 0, 1, 6, 0, 7, 0, 2, 0, 6, 0, 3, 1, 0, 0, 7, 12, 5, 7, 
    0, 2, 8, 1, 9, 12, 4, 1, 0, 0, 1, 1, 0, 25, 0, 0, 13, 1, 
    5, 2, 7, 1, 4, 22, 6, 12, 2), mcgill_total = c(0, 0, 0, 0, 
    0, 0, 9, 0, 0, 4, 0, 1, 0, 5, 0, 0, 0, 0, 0, 38, 34, 16, 
    0, 0, 0, 5, 2, 14, 0, 0, 0, 25, 0, 0, 21, 0, 9, 0, 0, 42, 
    12, 4, 3, 44, 10, 18, 50, 39, 42, 9), TIB = c(7, 7.5, 8.5, 
    8, 9.5, 8.5, 7.5, 8.5, 7.5, 7, 9, 8, 8, 32, 31, 8.5, 32, 
    8.5, 8.75, 8, 32, 8, 7.5, 32.25, 6, 30, 7.5, 9, 8.5, 9, 30.5, 
    9, 30, 31, 7.25, 7, 8, 7.5, 9, 9, 30.75, 30.5, 32, 6.5, 32, 
    7, 6, 7.75, 8.5, 8.5)), row.names = c(NA, 50L), class = "data.frame")

```

```{r ---> Demo, eval=TRUE, echo=FALSE, message=FALSE}
#		GROUP BY SEX INFORMATION
groups_x_sex <- zq.dat %>%
	group_by(group, sex) %>% 
	tally()

groups_x_sex %>% 
	kable(align = "c", padding = 4) %>% 
	kable_styling("striped", full_width = F) %>% 
	collapse_rows(columns = 1:2, valign = "top") %>% 
	row_spec(0, bold = T, color = "white", background = "#461B7E" )

```

```{r ---> plots}
plot(zq.dat)


```
