---
title: "PSQI scoring"
author: "Jason"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CREATE DATASET
```{r ---> PSQI dataset}
#		PSQI DATA
# gather psqi variables into separate spreadsheet:
dat.psqi <- dat1[,c(1,425,769,
					  grep("pittsburgh", colnames(dat1)),
					  grep("psqi", colnames(dat1)))]
#grep("timestamp", colnames(dat.raw))

colnames(dat.psqi)
# label(dat.psqi)
# view(dat.psqi)

#	REORGANIZE VARIABLES
dat.psqi <- dat.psqi %>% select(1:7,43,everything()) 
dat.psqi <- dat.psqi %>% select(1:11,44,everything()) 
dat.psqi <- dat.psqi %>% select(1:14,45,everything()) 
dat.psqi <- dat.psqi %>% select(1:16,46,everything()) 
dat.psqi <- dat.psqi %>% select(1:18,47,everything())
dat.psqi <- dat.psqi %>% select(1:20,48,everything())
dat.psqi <- dat.psqi %>% select(1:22,49,everything())
dat.psqi <- dat.psqi %>% select(1:24,50,everything())
dat.psqi <- dat.psqi %>% select(1:26,51,everything())
dat.psqi <- dat.psqi %>% select(1:28,52,everything())
dat.psqi <- dat.psqi %>% select(1:30,53,everything())
dat.psqi <- dat.psqi %>% select(1:32,54,everything())
dat.psqi <- dat.psqi %>% select(1:35,55,everything())
dat.psqi <- dat.psqi %>% select(1:37,56,everything())
dat.psqi <- dat.psqi %>% select(1:39,57,everything())
dat.psqi <- dat.psqi %>% select(1:41,psqi_8b.factor,
								psqi_9, psqi_9.factor,
								everything())
dat.psqi <- dat.psqi %>% select(1:45,
								psqi_10.factor,
								psqi_10a, psqi_10a.factor,
								psqi_10b, psqi_10b.factor,
								psqi_10c, psqi_10c.factor,
								psqi_10d, psqi_10d.factor,
								psqi_10e, 
								psqi_10e1, psqi_10e1.factor,
								everything())

dat.psqi <- dat.psqi %>% select(1:2,group.factor,everything())

colnames(dat.psqi)

write.csv(dat.psqi, "PSQI_rawData_13April2020.csv", row.names = FALSE)

# ls()
```

# TIME VARIABLES
```{r ---> TIME IN BED v1}
dat.psqi$bedtime  <- dat.psqi$psqi_1
dat.psqi$bt.sleep <- dat.psqi$psqi_1a.factor
dat.psqi$waketime <- dat.psqi$psqi_3
dat.psqi$wt.wake <- dat.psqi$psqi_3a.factor

#		FOR FORUM HELP VERSION #1
#		GOING TO SLEEP AND WAKING UP ON THE SAME DAY RESULTS IN 24+ HOURS
dat.psqi <- dat.psqi %>%
	mutate_all(.funs = as.character) %>%
	mutate_at(.vars = c("bt.sleep", "wt.wake"),
			  .funs = ~ gsub(pattern = ".",
			  			   replacement = "",
			  			   x = .x,
			  			   fixed = TRUE)) %>%
	mutate(Sleep = as.POSIXct(x = paste(bedtime, bt.sleep),
							  format = "%I:%M %p"),
		   Wake = as.POSIXct(x = paste(waketime, wt.wake),
		   				  format = "%I:%M %p") +
		   	as.difftime(tim = 1, units = "days"),
		   `Time in bed` = Wake - Sleep)

#		CRUDE FIX FOR THE 24+ HOUR ISSUE
dat.psqi$TIB  <- as.numeric(dat.psqi$`Time in bed`)
round(dat.psqi$TIB  <- if_else(dat.psqi$TIB < 24,
					  dat.psqi$TIB,
					  dat.psqi$TIB - 24), 2)


write.csv(dat.psqi, "PSQI_rawData_April2020_v1.csv", row.names = FALSE)

colnames(dat.psqi)

```

```{r ---> chr to num}
dat.psqi$psqi_2 <- as.numeric(dat.psqi$psqi_2)
dat.psqi$psqi_4 <- as.numeric(dat.psqi$psqi_4)
dat.psqi$psqi_5a <- as.numeric(dat.psqi$psqi_5a)
dat.psqi$psqi_5b <- as.numeric(dat.psqi$psqi_5b)
dat.psqi$psqi_5c <- as.numeric(dat.psqi$psqi_5c)
dat.psqi$psqi_5d <- as.numeric(dat.psqi$psqi_5d)
dat.psqi$psqi_5e <- as.numeric(dat.psqi$psqi_5e)
dat.psqi$psqi_5f <- as.numeric(dat.psqi$psqi_5f)
dat.psqi$psqi_5g <- as.numeric(dat.psqi$psqi_5g)
dat.psqi$psqi_5h <- as.numeric(dat.psqi$psqi_5h)
dat.psqi$psqi_5i <- as.numeric(dat.psqi$psqi_5i)
dat.psqi$psqi_5othera <- as.numeric(dat.psqi$psqi_5othera)
dat.psqi$psqi_7 <- as.numeric(dat.psqi$psqi_7)
dat.psqi$psqi_8a <- as.numeric(dat.psqi$psqi_8a)

dat.psqi$psqi_9 <- as.numeric(dat.psqi$psqi_9)
dat.psqi$psqi_component1 <- as.numeric(dat.psqi$psqi_component1)


#		REPLACE "NA" WITH 0
dat.psqi$psqi_5othera <- dat.psqi$psqi_5othera %>% replace_na(0)


```

```{r ---> PSQI Comp 1}
#		COMPONENT 1 = QUESTION 9
dat.psqi$psqi_Comp1 <- dat.psqi$psqi_component1

#		SCORE QUESTION 1
# Component 1: Subjective sleep quality—question 9
# Response, Component Score to Q9 
# Very good, 0
# Fairly good, 1
# Fairly bad, 2
# Very bad, 3

dat.psqi <- dat.psqi %>% relocate(psqi_Comp1, .after = last_col())

```

```{r ---> Component 2}
# Component 2: Sleep latency—questions 2 and 5a

dat.psqi$Q2 <- dat.psqi$psqi_2
dat.psqi$Q5a <- dat.psqi$psqi_5a

dat.psqi  <- dat.psqi %>%
	mutate(
		Q2score1 = case_when(
			Q2 <= 15 ~ 0,
			Q2 >= 16 & Q2 <= 30 ~ 1,
			Q2 >= 31 & Q2 <= 60 ~ 2,
			Q2 > 60 ~ 3,
			TRUE ~ as.numeric(Q2)
		)
	)

dat.psqi <- dat.psqi %>% 
	mutate(
		Q5aScore1 = case_when(
			Q5a == 1 ~ 0,
			Q5a == 2 ~ 1,
			Q5a == 3 ~ 2,
			Q5a == 4 ~ 3,
			TRUE ~ as.numeric(Q5a)
		)
	)


dat.psqi  <- dat.psqi %>%
	rowwise() %>%
	mutate(
		Q2and5 = sum(c(Q2score1, Q5aScore1), na.rm = TRUE)
	) %>%
	ungroup()

dat.psqi <- dat.psqi %>% 
	mutate(
		psqi_Comp2 = case_when(
			Q2and5 == 0 ~ 0,
			Q2and5 >= 1 & Q2and5 <= 2 ~ 1,
			Q2and5 >= 3 & Q2and5 <= 4 ~ 2,
			Q2and5 >= 5 & Q2and5 <= 6 ~ 3,
			TRUE ~ as.numeric(Q2and5)
		)
	)

```

```{r ---> Component 3}
# Component 3: Sleep duration—question 4

dat.psqi$Q4 <- dat.psqi$psqi_4

dat.psqi  <- dat.psqi %>%
	mutate(
		psqi_Comp3 = case_when(
			Q4 > 7 ~ 0,
			Q4 >= 6 & Q4 <= 7 ~ 1,
			Q4 >= 5 & Q4 < 6 ~ 2,
			Q4 < 5 ~ 3,
			TRUE ~ as.numeric(Q4)
		)
	)

dat.psqi <- dat.psqi %>% relocate(Q4, .before = psqi_Comp1)

```

```{r ---> Component 4}
# Component 4: Sleep efficiency—questions 1, 3, and 4
# Sleep efficiency = (# hours slept/# hours in bed) X 100% 
#	= (Q4 / TIB) * 100
# hours slept—question 4
# hours in bed—calculated from responses to questions 1 and 3
# 	Sleep efficiency, Component score 
# 		> 85%, 0	
# 		75-84%, 1
# 		65-74%, 2
# 		< 65%, 3

dat.psqi$SE <- (dat.psqi$Q4 / dat.psqi$TIB) * 100

dat.psqi  <- dat.psqi %>%
	mutate(
		psqi_Comp4 = case_when(
			SE >= 85 ~ 0,
			SE >= 75 & SE < 85 ~ 1,
			SE >= 65 & SE < 75 ~ 2,
			SE < 65 ~ 3,
			TRUE ~ as.numeric(SE)
		)
	)

dat.psqi <- dat.psqi %>% relocate(SE, .before = psqi_Comp1)
```

```{r ---> Component 5}
# Sum of 5b to 5j scores, Component 5 score
# 0, 0
# 1-9, 1
# 10-18, 2 
# 19-27, 3

dat.psqi$psqi_5j <- dat.psqi$psqi_5othera # copy variable

#		REARRANGE COLUMNS - AGAIN
dat.psqi <- dat.psqi %>% relocate(psqi_5othera, .before = psqi_5b)
dat.psqi <- dat.psqi %>% relocate(psqi_5b, .before = psqi_Comp1)
dat.psqi <- dat.psqi %>% relocate(psqi_5c, .before = psqi_Comp1)
dat.psqi <- dat.psqi %>% relocate(psqi_5d, .before = psqi_Comp1)
dat.psqi <- dat.psqi %>% relocate(psqi_5e, .before = psqi_Comp1)
dat.psqi <- dat.psqi %>% relocate(psqi_5f, .before = psqi_Comp1)
dat.psqi <- dat.psqi %>% relocate(psqi_5g, .before = psqi_Comp1)
dat.psqi <- dat.psqi %>% relocate(psqi_5h, .before = psqi_Comp1)
dat.psqi <- dat.psqi %>% relocate(psqi_5i, .before = psqi_Comp1)
dat.psqi <- dat.psqi %>% relocate(psqi_5j, .before = psqi_Comp1)


#		RESCORE THE RESPONSES - ORIG = 1-4; NEW = 0-3
#		THIS REPLACES THE VALUES IN THE ORIGINAL VARIABLES
dat.psqi <- dat.psqi %>% 
	mutate_at(vars(matches("psqi_5[b-i]$")), ~ . - 1)

#		RESCORING THE LONG WAY
dat.psqi$Q5b <- dat.psqi$psqi_5b -1
dat.psqi$Q5c <- dat.psqi$psqi_5c -1
dat.psqi$Q5d <- dat.psqi$psqi_5d -1
dat.psqi$Q5e <- dat.psqi$psqi_5e -1
dat.psqi$Q5f <- dat.psqi$psqi_5f -1
dat.psqi$Q5g <- dat.psqi$psqi_5g -1
dat.psqi$Q5h <- dat.psqi$psqi_5h -1
dat.psqi$Q5i <- dat.psqi$psqi_5i -1
dat.psqi$Q5j <- dat.psqi$psqi_5j 

#		SUMMING THE SCORES
dat.psqi  <- dat.psqi %>%
	rowwise() %>%
	mutate(
		Q5s = sum(c(Q5b, Q5c, Q5d, Q5e, Q5f, Q5g, Q5h, Q5i, Q5j), na.rm = TRUE)
	) %>%
	ungroup()


# Sum of 5b to 5j scores, Component 5 score
# 0, 0
# 1-9, 1
# 10-18, 2 
# 19-27, 3
#		CONVERTING TO COMPONENT SCORE
dat.psqi <- dat.psqi %>% 
	mutate(
		psqi_Comp5 = case_when(
			Q5s < 1 ~ 0,
			Q5s >= 1 & Q5s <=9 ~ 1,
			Q5s >= 10 & Q5s <=18 ~ 1,
			Q5s >= 19 & Q5s <=27 ~ 1,
			TRUE ~ as.numeric(Q5s)
		)
	)



dat.psqi <- dat.psqi %>% relocate(psqi_Comp1, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp2, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp3, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp4, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp5, .after = last_col())




```

```{r ---> Component 6}
# Component 6: Use of sleep medication—question 6
# Response to Q6, Component 6 score
# Not during past month, 0
# Less than once a week, 1 
# Once or twice a week, 2
# Three or more times a week, 3

dat.psqi$psqi_Comp6 <- as.numeric(dat.psqi$psqi_6)

```

```{r ---> Component 7}
# 	Component 7: SUM Daytime dysfunction—questions 7 and 8
# Sum of Q7 and Q8 subscores, COMPONENT SCORE 
# 0,0
# 1-2 1 
# 3-4 2 
# 5-6 3

#		SUM QUESTIONS 7 AND 8a
dat.psqi  <- dat.psqi %>%
	rowwise() %>%
	mutate(
		Q7and8a = sum(c(psqi_7, psqi_8a), na.rm = TRUE)
	) %>%
	ungroup()

#		SCORE COMPONENT 7
dat.psqi  <- dat.psqi %>%
	mutate(
		psqi_Comp7 = case_when(
			Q7and8a > 1 ~ 0,
			Q7and8a >= 1 & Q7and8a <= 2 ~ 1,
			Q7and8a >= 3 & Q7and8a <= 4 ~ 2,
			Q7and8a >= 5 & Q7and8a <= 6 ~ 3,
			TRUE ~ as.numeric(Q7and8a)
		)
	)

dat.psqi <- dat.psqi %>% relocate(psqi_Comp1, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp2, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp3, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp4, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp5, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp6, .after = last_col())
dat.psqi <- dat.psqi %>% relocate(psqi_Comp7, .after = last_col())

```

```{r ---> Global Score}
# Global PSQI Score: Sum of seven component scores:

dat.psqi  <- dat.psqi %>%
	rowwise() %>%
	mutate(
		psqi_Global = sum(c(psqi_Comp1, psqi_Comp2, psqi_Comp3,
							psqi_Comp4, psqi_Comp5, psqi_Comp6,
							psqi_Comp7), na.rm = TRUE)
	) %>%
	ungroup()

```

#MERGE BACK INTO MAIN DATASET
```{r ---> Merge into main dataset}
#		COMBINING 2 DATASETS

#		CREATING SMALL PSQI DATASET
psqiSM  <- dat.psqi %>% dplyr::select("ID","psqi_Comp1", "psqi_Comp2", "psqi_Comp3",
									  "psqi_Comp4", "psqi_Comp5", "psqi_Comp6",
									  "psqi_Comp7", "psqi_Global")

dat1 <- merge(dat1, psqiSM, by = "ID")

ls()
```


<!-- # FORUM QUESTIONS - RESPONSES -->
<!-- ```{r ---> Recreate a dataset} -->
<!-- #		USE THE COMMAND BELOW TO RECREATE A DATASET FOR THE FORUM -->
<!-- #dput(head(dat.time, 20)) -->

<!-- ``` -->

<!-- ```{r ---> for loop} -->
<!-- #		Question 1 - rescoring psqi_5 questions -->
<!-- #		REDUCED DATASET -->

<!-- psqi.Q5 <- dat.psq2 %>% select(1,72:80)  -->
<!-- dput(head(psqi.Q5, 100)) -->

<!-- psqi_Q5s <- c("b","c","d","e","f","g","h","i") -->
<!-- j <- "psqi_5" -->
<!-- k <- "psQ5" -->


<!-- for (i in psqi_Q5s){ -->
<!-- 	q <- paste0(j, i) # original variable -->
<!-- 	y <- paste0(k,i) # new scored variable -->
<!-- 	# for(z in 1:8){  -->
<!-- 		psqi.Q5  <- psqi.Q5 %>% -->
<!-- 			mutate( -->
<!-- 				y = case_when( -->
<!-- 					q == 1 ~ 0, -->
<!-- 					q == 2 ~ 1, -->
<!-- 					q == 3 ~ 2, -->
<!-- 					q == 4 ~ 3 #, -->
<!-- 					# TRUE ~ NA_integer_ -->
<!-- 					#TRUE ~ as.numeric(q) -->
<!-- 				) -->
<!-- 			) -->
<!-- 		# } -->
<!-- } -->

<!-- #		RESPONSE TO QUESTION #1` -->
<!-- #			THIS DOES THE JOB BUT DOESN’T CREATE NEW COLUMNS -->
<!-- psqi.Q5 <- psqi.Q5 %>%  -->
<!-- 	mutate_at(vars(matches("psqi_5[b-i]$")), ~ . -1) -->


<!-- ``` -->


<!-- #SCRAP STUFF -->
<!-- ```{r ---> SCRAP} -->

<!-- #			THESE DON'T WORK AND I DON'T KNOW WHY -->
<!-- # dat.psqi  <- dat.psqi %>% -->
<!-- 	rowwise() %>% -->
<!-- 	mutate( -->
<!-- 		Q5ss = sum(c("Q5[b-j]"), na.rm = TRUE) -->
<!-- 	) %>% -->
<!-- 	ungroup() -->





<!-- dat.psqi <- dat.psqi %>% -->
<!-- 	rowwise() %>% -->
<!-- 	mutate( -->
<!-- 		Q5ss = sum(vars(matches("Q5[b-j]")), na.rm = TRUE) -->
<!-- 	) %>% -->
<!-- 	ungroup() -->







<!-- #		SUM RESPONSES -->
<!-- psqi.Q5 <- psqi.Q5 %>%  -->
<!-- 	rowwise() %>%  -->
<!-- 	mutate( -->
<!-- 		vars(matches("psqi_5[b-i]$")), sum, na.rm = TRUE)  %>%  -->
<!-- 	ungroup() -->

<!-- psqi.Q5 <- psqi.Q5 %>%  -->
<!-- 	rowwise() %>%  -->
<!-- 	mutate( -->
<!-- 	SumQ5 = sum(vars(matches("psqi_5[b-i]$")), -->
<!-- 				sum, na.rm = TRUE))  %>%  -->
<!-- 	ungroup() -->


<!-- psqi.Q5  <- psqi.Q5 %>% -->
<!-- 	rowwise() %>% -->
<!-- 	mutate( -->
<!-- 		Q5bto5j = sum(c(Q2score1, Q5aScore1), na.rm = TRUE) -->
<!-- 	) %>% -->
<!-- 	ungroup() -->



<!-- psqi.Q5 %>%  -->
<!--   mutate_at(vars(matches("psqi_5[b-i]")), list("rescored" = . - 1)) -->





<!-- psqi.Q5 %>% mutate_at(vars(matches("psqi_5[b-i]")), ~ , na.rm = TRUE) -->







<!-- z <- iris -->

<!-- k <- iris %>% mutate(across(matches("Sepal"), log)) -->

<!-- #	NEW VALUES FOR 5 SUBQUESTIONS -->
<!-- # dat.psqi$psqi_5a <- as.numeric(dat.psqi$psqi_5a) -->
<!-- # dat.psqi$psqi_5b <- as.numeric(dat.psqi$psqi_5b) -->
<!-- # dat.psqi$psqi_5c <- as.numeric(dat.psqi$psqi_5c) -->
<!-- # dat.psqi$psqi_5d <- as.numeric(dat.psqi$psqi_5d) -->
<!-- # dat.psqi$psqi_5e <- as.numeric(dat.psqi$psqi_5e) -->
<!-- # dat.psqi$psqi_5f <- as.numeric(dat.psqi$psqi_5f) -->
<!-- # dat.psqi$psqi_5g <- as.numeric(dat.psqi$psqi_5g) -->
<!-- # dat.psqi$psqi_5h <- as.numeric(dat.psqi$psqi_5h) -->
<!-- # dat.psqi$psqi_5i <- as.numeric(dat.psqi$psqi_5i) -->







<!-- jj  <- "dat.psqi$psqi_5" -->
<!-- h <- "b" -->
<!-- k <- paste0(j, h) -->
<!-- dat.psqi2 <- dat.psqi -->

<!-- psqi_Q5s <- c("b","c","d","e","f","g","h","i") -->
<!-- j <- "psqi_5" -->
<!-- k <- "psQ5" -->
<!-- for (i in psqi_Q5s){ -->
<!-- 	q <- paste0(j, i) # original variable -->
<!-- 	y <- paste0(k,i) # new scored variable -->
<!-- 	# for(z in 1:8){  -->
<!-- 		dat.psqi2  <- dat.psqi2 %>% -->
<!-- 		mutate( -->
<!-- 			y = case_when( -->
<!-- 				q == 1 ~ 0, -->
<!-- 				q == 2 ~ 1, -->
<!-- 				q == 3 ~ 2, -->
<!-- 				q == 4 ~ 3 #, -->
<!-- 				# TRUE ~ NA_integer_ -->
<!-- 				#TRUE ~ as.numeric(q) -->
<!-- 			) -->
<!-- 		) -->
<!-- 	# } -->
<!-- } -->







<!-- #dput(head(dat.time, 20)) -->









<!-- head(dat.time) -->
<!-- class(dat.time$bedtime) -->
<!-- class(dat.time$bt.sleep) -->
<!-- class(dat.time$waketime) -->
<!-- class(dat.time$wt.wake) -->



<!-- # minuteave$minutes <- ymd_hms(minuteave$minutes) -->

<!-- dat.time$bedtime2  <- as.character(dat.time$bedtime) -->

<!-- dat.time$bedtime3 <- as.POSIXct(dat.time$bedtime2, -->
<!--                        format = '%H:%M') -->

<!-- dat.time$bedtime5 <- as.POSIXct(dat.time$bedtime3, -->
<!--                        format = '%H:%M') -->


<!-- view(dat.time) -->


<!-- dat.time$bedtime4  <- hms(dat.time$bedtime3) -->

<!-- dat.time$bedtime3  <- as_date(dat.time$bedtime2) -->



<!-- library(chron) -->
<!-- x <- chron(times=time) -->

<!-- library(anytime) -->
<!-- # R> anytime(as.factor("2013-06-01 08:07:00")) -->
<!-- # [1] "2013-06-01 08:07:00 CDT" -->
<!-- dat.time$bedtime4  <- anytime(dat.time$bedtime3) -->


<!-- dat.time$bedtime3 <- chron(dat.time$bedtime2) -->

<!-- # dat.time$btAM <- grepl("AM", dat.time$bedtime) -->
<!-- # dat.time$wtAM <- grepl("AM", dat.time$waketime) -->


<!-- if (dat.time$bt.sleep = "P.M.") { -->
<!-- 	dat.time$bedtime2 = (dat.time$bedtime + 12) -->
<!-- } -->












<!-- # dput(head(dat.time, 3)) -->




<!-- #####PSQI scoring. Make a new dataframe to put all the PSQI variables into. #### -->
<!-- psqi <- dat.bl[,c(1,3)] -->

<!-- # Sleep Quality: This is scored so that higher score = higher quality sleep. -->
<!-- psqi$SQ <- 3-dat.bl$psqi_9 -->


<!-- # require(lubridate) -->

<!-- ##### retain Baseline data only: #### -->
<!-- # dat.bl <- dat1[dat1$redcap_event_name == "baseline_data_arm_1",] -->
<!-- # colnames(dat.bl) # Baseline data -->

<!-- #		RECREATING MEREDITH'S PROCESS FOR CREATING A SMALLER DATASET: USEFUL??? -->
<!-- # dat.rc.scored  <- dat.bl[,c(1,3,408:422,425,769)] -->
<!-- # colnames(dat.rc.scored) -->
<!-- # view(dat.rc.scored) -->


<!-- #### Score Variables #### -->







<!-- ``` -->

<!-- ```{r ---> TIME IN BED v2} -->
<!-- dat.psqi$bedtime  <- dat.psqi$psqi_1 -->
<!-- dat.psqi$bt.sleep <- dat.psqi$psqi_1a.factor -->
<!-- dat.psqi$waketime <- dat.psqi$psqi_3 -->
<!-- dat.psqi$wt.wake <- dat.psqi$psqi_3a.factor -->


<!-- #		VERSION #2 FROM THE FORUMS -->
<!-- library(dplyr, warn.conflicts = FALSE) -->
<!-- #> Warning: package 'dplyr' was built under R version 3.6.3 -->

<!-- dat.psqi <- dat.psqi %>% -->
<!-- 	mutate(Sleep = if_else(bt.sleep == "PM", -->
<!-- 						   true = as.POSIXct(x = paste(bedtime, bt.sleep),  -->
<!-- 						   				  format = "%I:%M %p"), # time in current date -->
<!-- 						   false = as.POSIXct(x = paste(bedtime, bt.sleep), -->
<!-- 						   				   format = "%I:%M %p") +  -->
<!-- 						   	as.difftime(tim = 1,  -->
<!-- 						   				units = "days")), # consider next day for times at/after midnight -->
<!-- 		   Wake = as.POSIXct(x = paste(waketime, wt.wake), -->
<!-- 		   				  format = "%I:%M %p") +  -->
<!-- 		   	as.difftime(tim = 1, units = "days"), # time in current date plus one day, equivalently time in next day -->
<!-- 		   `Time Difference` = difftime(time1 = Wake, -->
<!-- 		   							 time2 = Sleep, -->
<!-- 		   							 units = "hours")) %>%  # difference of the two times, guaranteed to be in [0, 24) -->
<!-- 	print(width = Inf) -->


<!-- ``` -->

<!-- ```{r ---> TIME IN BED v3} -->

<!-- #		CALCULATE BEDTIMES -->
<!-- #Time in bed calculation: -->
<!-- # names(data)[names(data) == 'participant_id'] <- 'ID' -->

<!-- dat.time <- tibble("bedtime" = dat.psqi$psqi_1, -->
<!-- 				   "bt.sleep"= dat.psqi$psqi_1a.factor, -->
<!-- 				   "waketime" = dat.psqi$psqi_3, -->
<!-- 				   "wt.wake" = dat.psqi$psqi_3a.factor) -->




<!-- #		VERSION #2 FROM THE FORUMS -->
<!-- library(dplyr, warn.conflicts = FALSE) -->
<!-- #> Warning: package 'dplyr' was built under R version 3.6.3 -->
<!-- dat.time <- dat.time %>% -->
<!-- 	mutate(Sleep = if_else(bt.sleep == "PM", -->
<!-- 						   true = as.POSIXct(x = paste(bedtime, bt.sleep),  -->
<!-- 						   				  format = "%I:%M %p"), # time in current date -->
<!-- 						   false = as.POSIXct(x = paste(bedtime, bt.sleep), -->
<!-- 						   				   format = "%I:%M %p") +  -->
<!-- 						   	as.difftime(tim = 1,  -->
<!-- 						   				units = "days")), # consider next day for times at/after midnight -->
<!-- 		   Wake = as.POSIXct(x = paste(waketime, wt.wake), -->
<!-- 		   				  format = "%I:%M %p") +  -->
<!-- 		   	as.difftime(tim = 1, units = "days"), # time in current date plus one day, equivalently time in next day -->
<!-- 		   `Time Difference` = difftime(time1 = Wake, -->
<!-- 		   							 time2 = Sleep, -->
<!-- 		   							 units = "hours")) %>%  # difference of the two times, guaranteed to be in [0, 24) -->
<!-- 	print(width = Inf) -->

<!-- ``` -->

<!-- ```{r ---> TIME IN BED v4} -->


<!-- #		FOR FORUM HELP VERSION #1 -->
<!-- #		GOING TO SLEEP AND WAKING UP ON THE SAME DAY RESULTS IN 24+ HOURS -->
<!-- dat.time <- dat.time %>% -->
<!-- 	mutate_all(.funs = as.character) %>% -->
<!-- 	mutate_at(.vars = c("bt.sleep", "wt.wake"), -->
<!-- 			  .funs = ~ gsub(pattern = ".", -->
<!-- 			  			   replacement = "", -->
<!-- 			  			   x = .x, -->
<!-- 			  			   fixed = TRUE)) %>% -->
<!-- 	mutate(Sleep = as.POSIXct(x = paste(bedtime, bt.sleep), -->
<!-- 							  format = "%I:%M %p"), -->
<!-- 		   Wake = as.POSIXct(x = paste(waketime, wt.wake), -->
<!-- 		   				  format = "%I:%M %p") + -->
<!-- 		   	as.difftime(tim = 1, units = "days"), -->
<!-- 		   `Time in bed2` = Wake - Sleep) -->

<!-- #		CRUDE FIX FOR THE 24+ HOUR ISSUE -->
<!-- dat.time$TIB  <- dat.time$`Time in bed2` -->
<!-- round(dat.time$TIB  <- if_else(dat.time$TIB < 24, -->
<!-- 					  dat.time$TIB, -->
<!-- 					  dat.time$TIB - 24), 2) -->


<!-- write.csv(dat.psqi, "PSQI_rawData_April2020.csv", row.names = FALSE) -->

<!-- ``` -->

<!-- ```{r ---> TIME IN BED #2 ORIG} -->

<!-- #		CALCULATE BEDTIMES -->
<!-- #Time in bed calculation: -->
<!-- # names(data)[names(data) == 'participant_id'] <- 'ID' -->

<!-- # dat.time <- tibble("bedtime" = dat.psqi$psqi_1, -->
<!-- # 				   "bt.sleep"= dat.psqi$psqi_1a.factor, -->
<!-- # 				   "waketime" = dat.psqi$psqi_3, -->
<!-- # 				   "wt.wake" = dat.psqi$psqi_3a.factor) -->

<!-- dat.psqiORIG  <- dat.psqi -->

<!-- dat.psqi$bedtime  <- dat.psqi$psqi_1 -->
<!-- dat.psqi$bt.sleep <- dat.psqi$psqi_1a.factor -->
<!-- dat.psqi$waketime <- dat.psqi$psqi_3 -->
<!-- dat.psqi$wt.wake <- dat.psqi$psqi_3a.factor -->


<!-- #		VERSION #2 FROM THE FORUMS -->
<!-- library(dplyr, warn.conflicts = FALSE) -->
<!-- #> Warning: package 'dplyr' was built under R version 3.6.3 -->
<!-- dat.time <- dat.time %>% -->
<!-- 	mutate(Sleep = if_else(bt.sleep == "PM", -->
<!-- 						   true = as.POSIXct(x = paste(bedtime, bt.sleep),  -->
<!-- 						   				  format = "%I:%M %p"), # time in current date -->
<!-- 						   false = as.POSIXct(x = paste(bedtime, bt.sleep), -->
<!-- 						   				   format = "%I:%M %p") +  -->
<!-- 						   	as.difftime(tim = 1,  -->
<!-- 						   				units = "days")), # consider next day for times at/after midnight -->
<!-- 		   Wake = as.POSIXct(x = paste(waketime, wt.wake), -->
<!-- 		   				  format = "%I:%M %p") +  -->
<!-- 		   	as.difftime(tim = 1, units = "days"), # time in current date plus one day, equivalently time in next day -->
<!-- 		   `Time Difference` = difftime(time1 = Wake, -->
<!-- 		   							 time2 = Sleep, -->
<!-- 		   							 units = "hours")) %>%  # difference of the two times, guaranteed to be in [0, 24) -->
<!-- 	print(width = Inf) -->


<!-- ``` -->

